# Generated by Django 6.0.3 on 2026-04-07 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jo_number', models.CharField(max_length=20, unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('order_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_produced_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('current_stock_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reorder_point_kg', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExtrusionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_no', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('roll_weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wastage_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('operator_name', models.CharField(max_length=50)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrusion_logs', to='production.joborder')),
            ],
        ),
    ]
