# Generated by Django 6.0.3 on 2026-04-08 10:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtrusionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_no', models.CharField(max_length=10)),
                ('shift', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Night')], max_length=10)),
                ('operator_name', models.CharField(default='Extrusion Op', max_length=50)),
                ('target_amount_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_output_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_wastage_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jo_number', models.CharField(max_length=20, unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('po_number', models.CharField(blank=True, default='-', max_length=50)),
                ('target_delivery_date', models.DateField(blank=True, null=True)),
                ('product_dimension', models.CharField(default='', help_text='e.g., 230 x 240 x 0.03', max_length=100)),
                ('printing_required', models.BooleanField(default=False)),
                ('sealing_required', models.BooleanField(default=False)),
                ('slitting_required', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='-')),
                ('wastage_buffer_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('order_quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_est_material_kg', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_extruded_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cut_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_packed_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_shipped_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_completed', models.BooleanField(default=False, help_text='Mark as true when the entire order is finished.')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('current_stock_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reorder_point_kg', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExtrusionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('roll_weight_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('wastage_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.extrusionsession')),
            ],
        ),
        migrations.AddField(
            model_name='extrusionsession',
            name='job_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrusion_sessions', to='production.joborder'),
        ),
        migrations.CreateModel(
            name='DispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateTimeField(auto_now_add=True)),
                ('shipped_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_order_no', models.CharField(blank=True, max_length=50)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='production.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='CuttingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_no', models.CharField(max_length=10)),
                ('shift', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Night')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operator_name', models.CharField(max_length=50)),
                ('output_kg', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('wastage_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_logs', to='production.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='PackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operator_name', models.CharField(max_length=50)),
                ('packing_size_kg', models.DecimalField(decimal_places=2, help_text='KG per Bag/Pallet', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity_packed', models.IntegerField(help_text='Number of Bags/Pallets', validators=[django.core.validators.MinValueValidator(1)])),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_logs', to='production.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operator_name', models.CharField(max_length=50)),
                ('is_substitution', models.BooleanField(default=False)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='production.joborder')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocated_kg', models.DecimalField(decimal_places=2, help_text='Physical stock reserved for this job', max_digits=10)),
                ('shortfall_kg', models.DecimalField(decimal_places=2, default=0, help_text='Hypothetical stock (Needs Purchasing)', max_digits=10)),
                ('actual_used_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='production.joborder')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
            ],
        ),
        migrations.AddField(
            model_name='joborder',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.recipe'),
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='production.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_used_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.extrusionsession')),
            ],
        ),
    ]
