# Generated by Django 6.0.3 on 2026-04-07 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='joborder',
            old_name='total_produced_kg',
            new_name='total_cut_kg',
        ),
        migrations.AddField(
            model_name='extrusionlog',
            name='shift',
            field=models.CharField(choices=[('AM', 'Morning'), ('PM', 'Night')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joborder',
            name='product_dimension',
            field=models.CharField(default='', help_text='e.g., 230 x 240 x 0.03', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joborder',
            name='total_est_material_kg',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='joborder',
            name='total_extruded_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='joborder',
            name='total_packed_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='joborder',
            name='wastage_buffer_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='CuttingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_no', models.CharField(max_length=10)),
                ('shift', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Night')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('output_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wastage_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('operator_name', models.CharField(max_length=50)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_logs', to='production.joborder')),
            ],
        ),
        migrations.CreateModel(
            name='PackingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('packing_size_kg', models.DecimalField(decimal_places=2, help_text='KG per Bag/Pallet', max_digits=6)),
                ('quantity_packed', models.IntegerField(help_text='Number of Bags/Pallets')),
                ('operator_name', models.CharField(max_length=50)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_logs', to='production.joborder')),
            ],
        ),
        migrations.AddField(
            model_name='joborder',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.recipe'),
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='production.recipe')),
            ],
        ),
    ]
