# Generated by Django 6.0.3 on 2026-04-09 02:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRestockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField(auto_now_add=True)),
                ('amount_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('supplier', models.CharField(blank=True, default='-', max_length=100)),
                ('po_number', models.CharField(blank=True, default='-', max_length=50)),
                ('recorded_by', models.CharField(default='Admin', max_length=50)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='production.rawmaterial')),
            ],
        ),
    ]
