# Generated by Django 6.0.3 on 2026-04-07 04:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttinglog',
            name='output_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='cuttinglog',
            name='wastage_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='extrusionlog',
            name='roll_weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='extrusionlog',
            name='wastage_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='product_dimension',
            field=models.CharField(default='', help_text='e.g., 230 x 240 x 0.03', max_length=100),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.recipe'),
        ),
        migrations.AlterField(
            model_name='packinglog',
            name='packing_size_kg',
            field=models.DecimalField(decimal_places=2, help_text='KG per Bag/Pallet', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='packinglog',
            name='quantity_packed',
            field=models.IntegerField(help_text='Number of Bags/Pallets', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
