# Generated by Django 6.0.3 on 2026-04-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_materialcategory_rawmaterial_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='total_cutting_wastage_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
