# Generated by Django 6.0.3 on 2026-04-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_cuttinglog_output_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='po_number',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='joborder',
            name='printing_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joborder',
            name='remarks',
            field=models.TextField(blank=True, default='-'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='sealing_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joborder',
            name='slitting_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joborder',
            name='target_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
