# Generated by Django 6.0.3 on 2026-04-08 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_joborder_po_number_joborder_printing_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocated_kg', models.DecimalField(decimal_places=2, help_text='Physical stock reserved for this job', max_digits=10)),
                ('shortfall_kg', models.DecimalField(decimal_places=2, default=0, help_text='Hypothetical stock (Needs Purchasing)', max_digits=10)),
                ('actual_used_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='production.joborder')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterial')),
            ],
        ),
    ]
