# Generated by Django 6.0.3 on 2026-04-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joborder',
            options={'ordering': ['is_completed', 'queue_position', 'target_delivery_date']},
        ),
        migrations.AddField(
            model_name='joborder',
            name='queue_position',
            field=models.PositiveIntegerField(default=100, help_text='Lower numbers run first (e.g., 1 is top priority). Use 100 for standard/un-queued jobs.'),
        ),
    ]
