# Generated by Django 6.0.3 on 2026-04-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_joborder_options_joborder_queue_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttinglog',
            name='job_order',
        ),
        migrations.RemoveField(
            model_name='cuttinglog',
            name='machine_no',
        ),
        migrations.RemoveField(
            model_name='cuttinglog',
            name='operator_name',
        ),
        migrations.RemoveField(
            model_name='cuttinglog',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='cuttinglog',
            name='wastage_kg',
        ),
        migrations.CreateModel(
            name='CuttingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_no', models.CharField(max_length=10)),
                ('shift', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Night')], max_length=10)),
                ('operator_name', models.CharField(blank=True, max_length=50, null=True)),
                ('input_roll_weight_kg', models.DecimalField(decimal_places=2, help_text='Weight of the roll loaded onto the machine', max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ENDED_EARLY', 'Ended Early')], default='ACTIVE', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_output_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_wastage_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('job_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_sessions', to='production.joborder')),
            ],
        ),
        migrations.AddField(
            model_name='cuttinglog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='production.cuttingsession'),
        ),
    ]
