# Generated by Django 6.0.3 on 2026-04-16 08:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_remove_cuttinglog_job_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrusionsession',
            name='final_wastage_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='extrusionsession',
            name='returned_material_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='extrusionsession',
            name='transferred_to_next_job_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='extrusionsession',
            name='unaccounted_variance_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
