# Generated by Django 6.0.3 on 2026-04-16 09:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_extrusionsession_final_wastage_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='total_extrusion_wastage_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
