# Generated by Django 6.0.3 on 2026-04-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_joborder_total_extrusion_wastage_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingsession',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='extrusionsession',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Increments on every update to prevent multi-tab collision.'),
        ),
    ]
