# Generated by Django 6.0.3 on 2026-04-20 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('production', '0011_cuttingsession_version_extrusionsession_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(help_text='User or operator who performed the action', max_length=50)),
                ('action_type', models.CharField(choices=[('SESSION_STARTED', 'Session Started'), ('SESSION_STOPPED', 'Session Stopped'), ('SESSION_PURGED', 'Session Purged & Reconciled'), ('MATERIAL_USED', 'Material Used / Deducted'), ('OUTPUT_LOGGED', 'Production Output Logged'), ('JOB_COMPLETED', 'Job Fully Completed')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='production__content_6645d5_idx'), models.Index(fields=['action_type'], name='production__action__4115fd_idx'), models.Index(fields=['timestamp'], name='production__timesta_809670_idx')],
            },
        ),
    ]
