# Generated by Django 6.0.3 on 2026-04-21 08:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='estimated_extrusion_target_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='joborder',
            name='estimated_material_required_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cutting_wastage_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5),
        ),
        migrations.AddField(
            model_name='recipe',
            name='extrusion_wastage_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='cuttingsession',
            name='input_roll_weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='extrusionsession',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='product_dimension',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='queue_position',
            field=models.PositiveIntegerField(default=100, help_text='Lower numbers run first. Use 100 for standard/un-queued jobs.'),
        ),
        migrations.AlterField(
            model_name='materialallocation',
            name='allocated_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='materialallocation',
            name='shortfall_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='packinglog',
            name='packing_size_kg',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='packinglog',
            name='quantity_packed',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
