# Generated by Django 6.0.3 on 2026-04-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_joborder_estimated_extrusion_target_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cutting_session_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='extrusion_session_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('SESSION_STARTED', 'Session Started'), ('SESSION_STOPPED', 'Session Stopped'), ('SESSION_PURGED', 'Session Purged & Reconciled'), ('MATERIAL_USED', 'Material Used / Deducted'), ('OUTPUT_LOGGED', 'Production Output Logged'), ('JOB_COMPLETED', 'Job Fully Completed'), ('YIELD_ADAPTATION', 'Recipe Yield Adapted')], max_length=50),
        ),
    ]
